### ISSUE TITLE
Flatpaked KeePassXC doesn't add SSH key to agent

### ISSUE THREAD

**Issue by kaymio** [flathub/org.keepassxc.KeePassXC#33] opened 2019-02-25 08:26 UTC
## Expected Behavior:
Follow this little [tutorial](https://blog.valouille.fr/post/2018-03-27-how-to-use-keepass-xc-with-ssh-agent/) to add a SSH key to the agent when "Add to agent" is clicked and the "apply" button has been hit, a green bar says something like "Entry successfully updated". The name of the key in the 'keybox' is updated with the name corresponding with the name in the file. Confirm that the key has been added with 
`ssh-add -l`
## Current Behavior
Repeat the same procedure and hit "apply", watch the green banner and see the right name appear in they 'keybox'. After another click the banner vanishes and the name changes back to 'id_ed25519' where the real name should be printed. When checking the SSH agent it says that there are no keys in the list.

## Possible Solution
Supposedly the flatpak version is not able to make contact with the SSH agent.

## Context
Usually keychain is used by me to add keys but its quite annoying. As I've switched to KeePassXC for all my other passwords, I also wanted to use it for my SSH keys.  

## Debug

KeePassXC - Version 2.3.4
Revision: 6fe821c
Distribution: Flatpak

Librarys:
- Qt 5.12.1
- libgcrypt 1.8.4

OS: Linux 4.20.11-zen2-1-zen
CPU-Architecture: x86_64
Kernel: linux 4.20.11-zen2-1-zen

Activated extensions:
- Auto-Type
- Browser Integration
- SSH Agent

**Comment by AsavarTzeth** [comment] 2019-03-24 10:11
First of all, thank you for the reproducing steps and sorry about the delay.

In order for this whole thing work I use the `ssh-auth` permission provided by flatpak. There is one caveat though; there are a great number of ssh-agents and some may work.

*See reference:* https://github.com/flatpak/flatpak/pull/1764

That said, I did manage to get this working, using `ssh-agent` as provided by openssh itself. On my system it automatically set `SSH_AUTH_SOCK` to `/run/user/1000/keyring/ssh`.

Some things that you could check:
- Which ssh-agent are you using?
- When setting the private key within KeePassXC, is the **"External file"** path entered similar to:
  `/run/user/1000/doc/7364eacc/flatpak_id`?
If not you may need to re-open the file using the **"Browse..."** button. Entering a path manually will not work.

**Comment by AsavarTzeth** [comment] 2020-01-03 12:25
Closing, since this does appear to work, even though it does require certain knowledge and manual configuration. Although that is to a certain degree true for all keepassxc distributions.

This issue is also outdated now that the document portal isn't used and `--filesystem=host` is used instead.

What can be done is perhaps improving documentation and setup instructions.

**Closed by AsavarTzeth** 2020-01-03 12:25 UTC
Labels: documentation
