### ISSUE TITLE
Cannot open existing database or import from KeePass and CSV

### ISSUE THREAD

**Issue by Bittyby** [flathub/org.keepassxc.KeePassXC#46] opened 2019-11-26 19:23 UTC
Good day.
I'm experiencing exactly the same problem: https://github.com/flathub/org.keepassxc.KeePassXC/issues/1

And something similar here:
https://github.com/flathub/com.visualstudio.code/issues/123

**Comment by AsavarTzeth** [comment] 2019-11-28 13:18
@Bittyby I don't see how this is possible any more. When this issue was raised I did not allow direct access to the host file system, which likely was the cause.

Now I set --filesystem=host which changes everything, which means KeePassXC can access all files directly. The idea is to remove this in time, but only when all issues have been resolved.

*You may answer here, I skimmed past the new issue.*

**Comment by AsavarTzeth** [comment] 2019-11-28 13:19
Nevertheless I will try my best to reproduce it. If that fails you would likely have to give me more to work on.

**Comment by Bittyby** [comment] 2019-11-28 16:38
Ok
1. Download http://archive.ubuntu.com/ubuntu/dists/bionic/main/installer-amd64/current/images/netboot/mini.iso and install.
2. Then log in as a regular user.
```
sudo passwd root
root
root
exit
```
Log in as root

3. 
```
apt -y --no-install-recommends install htop nano software-properties-common wget gnome-terminal
add-apt-repository ppa:oibaf/graphics-drivers
apt -y --no-install-recommends install xorg xserver-xorg-video-intel ssh

cd /tmp && wget https://debian.sur5r.net/i3/pool/main/s/sur5r-keyring/sur5r-keyring_2019.02.01_all.deb && dpkg -i sur5r-keyring_2019.02.01_all.deb
echo "deb https://debian.sur5r.net/i3/ $(grep '^DISTRIB_CODENAME=' /etc/lsb-release | cut -f2 -d=) universe" >> /etc/apt/sources.list.d/sur5r-i3.list
apt update && apt -y install i3

cp /etc/i3status.conf ~/.config/i3
cp /etc/i3/config ~/.config/i3
```

4.
````
add-apt-repository ppa:alexlarsson/flatpak
apt -y --no-install-recommends install flatpak
nano ~/.profile
XDG_DATA_DIRS="/var/lib/flatpak/exports/share:$XDG_DATA_DIRS"
reboot
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
```

5.
```
flatpak install flathub org.keepassxc.KeePassXC
flatpak override org.keepassxc.KeePassXC --filesystem=host

flatpak run org.keepassxc.KeePassXC
```

**Comment by AsavarTzeth** [comment] 2019-11-28 18:12
Could you tell me if its a CSV or a KeePass 1 database you are trying to import? I tried a CSV that I exported from an old LastPass account just now and it works perfectly fine.

If its a KeePass 1 file, what's the simplest way of creating one today? It would seem all modern versions of KeePass applications have removed support for it.

> flatpak override org.keepassxc.KeePassXC --filesystem=host

By the way, you no longer need to use that override. It has been the default on the stable branch for some time now.

**Comment by Bittyby** [comment] 2019-11-28 19:15
![1](https://user-images.githubusercontent.com/58167613/69828325-82c48680-122c-11ea-97d6-4a5a0ade7fe1.png)

**Comment by AsavarTzeth** [comment] 2019-12-02 13:20
I see. Well then we have a misunderstanding. In KeePassXC terms you are not at all trying to **import** a database. You are trying **open** a database, which is slightly different.

If you are having issues opening a file that is very strange indeed. Considering that nothing happens at all, I would guess that this is a portal related issue. I have seen that more commonly on Ubuntu bases.

**Comment by Bittyby** [comment] 2019-12-02 14:07
Sorry. You're right. I am trying to open, not import.

Yes you are right. I just can’t open it, and also any `File Manager` doesn’t see `KeePassXC`.

**Comment by AsavarTzeth** [comment] 2020-11-01 11:17
I'm going to close this because:
- I can't reproduce it. It works fine on my systems and there is no reason it shouldn't now that `--filesystem=host` is used.
- Nobody has had anything to add for a long time.
- The issue is old and out-of-date in more than one way.

This issue was likely never caused packaging or any of the patches. It sounds more like a xdg-desktop-portal issue, probably a linux distribution, and/or version, specific issue.

Feel free to comment if it is still an issue but I very much doubt there is anything I can do about it at this level.

**Closed by AsavarTzeth** 2020-11-01 11:17 UTC
Labels: can't reproduce, external issue, out-of-date, portal
