### ISSUE TITLE
Unable to connect to Browser Plugin or SSH Agent

### ISSUE THREAD

**Issue by kurobeats** [flathub/org.keepassxc.KeePassXC#19] opened 2018-06-11 05:49 UTC
Title says it all. The application is unable to connect to the Browser Plugin or SSH Agent.

I suspect this is by design as it is a containerised application but it should be considered that the security in this instance is affecting core (optional) functionality.

**Comment by AsavarTzeth** [comment] 2018-06-11 10:40
This is partly a duplicate of #13. See that issue for a great deal of detail about the browser extension.

The short version is that its not as simple as just allowing access to the required files & sockets.

It is either very difficult or impossible to make this work. This is especially true when the app relies on external resources, or running services.

Be assured that I am always exploring ways to make these features work and I do take suggestions.

To be clear, I am not ignoring these issues due to some security concern.

**Comment by kurobeats** [comment] 2018-06-11 21:17
thank you for your response.

**Comment by AsavarTzeth** [comment] 2018-06-26 19:07
Flatpak 0.99.1 introduced the ability to use `--socket=ssh-auth` to grant access to the ssh agent.

Since you probably have more experience than I with the KeePassXC ssh-agent feature, I would very much appreciate if you could test this with:

    flatpak run --socket=ssh-auth org.keepassxc.KeePassXC//stable

If this does not work, could you share more information on how things should look and behave when it does work?

**Comment by kurobeats** [comment] 2018-06-27 12:50
Looks like fedora 28 is running an older version:

`$ flatpak run --socket=ssh-auth org.keepassxc.KeePassXC//stable
error: Unknown socket type ssh-auth, valid types are: x11, wayland, pulseaudio, session-bus, system-bus, fallback-x11
$ flatpak --version
Flatpak 0.11.8.3`

**Comment by AsavarTzeth** [comment] 2018-06-27 13:52
Yeah it does not surprise me, since the 0.99.1 release is a pre-release for the stable 1.0.

For some reason Arch Linux happens to use it.

In either case I suppose I cannot rely upon it until 1.0 then.

On the bright side I finally fixed the browser integration. Just about to force a rebuild due to some Flathub issues earlier.

**Comment by hifi** [comment] 2018-07-26 23:49
I can confirm `--socket=ssh-auth` does make it work with Flatpak 0.99.3 pulled from their own PPA on Linux Mint 19.

**Comment by AsavarTzeth** [comment] 2018-07-27 07:30
Excelent! Thank you for testing.

Now we just need various distributions to catch up. At least it would make sense to wait for the next LTS (stable) release.

Then I can add this by default in the manifest.

**Closed** 2018-09-11 07:35 UTC
Labels: help wanted
