### ISSUE TITLE
Latest org.keepassxc.KeePassXC can't remember column settings

### ISSUE THREAD

**Issue by ghost** [flathub/org.keepassxc.KeePassXC#54] opened 2020-02-14 07:27 UTC
I need to hide every column one-by-one after every start. This issue appeared 1-2 weeks ago.

**Comment by corecontingency** [comment] 2020-03-16 00:39
I cannot seem to replicate; Keepassxc remembers what columns I previously hid when I reopen it, even when opening a different database. Are you still having this issue?

**Comment by AsavarTzeth** [comment] 2020-07-16 09:27
Neither can I. I sort of did once, but that seems to have been caused by me changing between test versions and resolved itself an additional app restart later.

**Comment by AsavarTzeth** [comment] 2020-11-01 09:35
Closing, due to not being reproduced and no longer being valid after several app and runtime updates.

Please comment if the issue persists.

**Closed by AsavarTzeth** 2020-11-01 09:35 UTC
Labels: can't reproduce
