### ISSUE TITLE
File paths in "Recent databases" are not real paths

### ISSUE THREAD

**Issue by amtlib-dot-dll** [flathub/org.keepassxc.KeePassXC#2] opened 2017-12-24 06:58 UTC
Instead, they are File Portal paths.
![screenshot from 2017-12-24 14-55-29](https://user-images.githubusercontent.com/8613971/34324837-da998074-e8ba-11e7-8f18-d8a5299354ad.png)

**Comment by aiamuzz** [comment] 2018-03-08 15:35
Yes ... i second this issue ... database paths aren't real ...

**Comment by AsavarTzeth** [comment] 2018-03-08 16:07
Please use emoticons to thumbs up instead of posting (me too) comments.

**Comment by aiamuzz** [comment] 2018-03-08 16:56
@AsavarTzeth ...

oh ... i didn't know ... does a thumbs-up emoticon a way to say that one is facing the same issue ?

**Comment by AsavarTzeth** [comment] 2018-03-08 17:32
Well that depends on what comment you thumbs up. A thumbs up on any comment generally means that you agree with it. In this context it can really only say that you experience this too, or otherwise agree that it is an issue.

So to answer you, yes if you thumbs up the original comment, which I see you did already.

It is very common that people don't know about this on GitHub though, since it is hidden under the emoticon menu.

**Comment by VosaXalo** [comment] 2018-10-11 17:42
I can confirm this issue also on KDE Neon with Plasma 5.14 and KeePassXC 2.3.4

**Comment by AsavarTzeth** [comment] 2019-04-20 08:24
Closing since the stable branch, for now has `--filesystem=host`.

**Closed by AsavarTzeth** 2019-04-20 08:24 UTC
Labels: enhancement, sandbox
