### ISSUE TITLE
High CPU load with the browser extension.

### ISSUE THREAD

**Issue by varjolintu** [flathub/org.keepassxc.KeePassXC#47] opened 2019-12-03 10:52 UTC
We've received multiple reports where Flatpak version of KeePassXC causes CPU load with Firefox and the browser integration. See: https://github.com/keepassxreboot/keepassxc-browser/issues/629

Any idea why this might happen?

**Comment by AsavarTzeth** [comment] 2019-12-14 13:36
Wow, that is interesting indeed... In my case Firefox can use up to around 150% of the CPU.

No, unfortunately I don't have any ideas at the moment. My first guess would be some recent regression on my part, but that was ruled out when I saw this first occurred with 2.4.3 in early October.

However, I have done some investigation of my own. Before I present the results:

1. I kill the extension and the cpu usage by using `pkill keepassxc-proxy`. This ends the cpu usage.
2. I re-trigger it by simply clicking "Reload" in the browser extension.
3. I am using `flatpak ps | grep keepassxc` and `pgrep keepassxc` and `top -u (pgrep firefox)` to verify the current state.

**When `keepassxc-proxy` is running**:

```
# -f is required to show all threads
strace -p (pgrep firefox) -f -c
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 54,96    2,194863          27     79604     14045 futex
 21,51    0,858811       34352        25           epoll_wait
 17,92    0,715526         220      3244           poll
  4,54    0,181199      181199         1           restart_syscall
  0,91    0,036289          11      3200           wait4
  0,06    0,002588          32        79        66 recvmsg
  0,03    0,001108          48        23           write
  0,03    0,001100          78        14           sendmsg
  0,02    0,000957         119         8           munmap
  0,02    0,000655          28        23           read
  0,00    0,000161          12        13           gettid
  0,00    0,000020          20         1           getpid
  0,00    0,000012          12         1           writev
------ ----------- ----------- --------- --------- ----------------
100.00    3,993289                 86236     14111 total
```

**When `keepassxc-proxy` is killed**:

```
pkill keepassxc-proxy
strace -p (pgrep firefox) -f -c
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 67,76    0,653934        2658       246        25 futex
 12,47    0,120376       10031        12           epoll_wait
 12,46    0,120264        6329        19           poll
  6,21    0,059910           6      9484           madvise
  0,79    0,007589        2529         3         2 restart_syscall
  0,11    0,001073          17        61        51 recvmsg
  0,05    0,000438          25        17           mmap
  0,03    0,000316          45         7           read
  0,03    0,000306          43         7           write
  0,02    0,000191           9        20           gettid
  0,02    0,000181          22         8           munmap
  0,01    0,000138          46         3           sendmsg
  0,01    0,000060           3        20           getpid
  0,01    0,000053          17         3           stat
  0,01    0,000050           2        20           sched_getaffinity
  0,00    0,000047          23         2           mprotect
  0,00    0,000042          42         1           unlink
  0,00    0,000042          21         2           getrusage
  0,00    0,000022          11         2           close
  0,00    0,000014          14         1           access
  0,00    0,000003           3         1           fstat
------ ----------- ----------- --------- --------- ----------------
100.00    0,965049                  9939        78 total
```

**Closer inspection**:

```
strace -p (pgrep firefox) -f -e futex -s 128 -c
# a small extract
...
17076 futex(0x7f74c182a3a8, FUTEX_WAKE_PRIVATE, 1) = 0
17223 futex(0x7f74c182a404, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
17076 futex(0x7f74c182a3a8, FUTEX_WAIT_PRIVATE, 2, NULL <unfinished ...>
17223 <... futex resumed>)              = 0
17223 futex(0x7f74c182a3a8, FUTEX_WAKE_PRIVATE, 1) = 1
17076 <... futex resumed>)              = 0
17223 futex(0x7f74ab2d7048, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
17076 futex(0x7f74c182a3a8, FUTEX_WAKE_PRIVATE, 1) = 0
17076 futex(0x7f74ab2d7048, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
17223 <... futex resumed>)              = 0
17076 <... futex resumed>)              = 1
17223 futex(0x7f74b0165070, FUTEX_WAIT_PRIVATE, 2, NULL <unfinished ...>
17076 futex(0x7f74b0165070, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
17223 <... futex resumed>)              = -1 EAGAIN (Resource temporarily unavailable)
17076 <... futex resumed>)              = 0
17223 futex(0x7f74b0165070, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
17076 futex(0x7f74c182a400, FUTEX_WAIT_BITSET_PRIVATE, 0, {tv_sec=20705, tv_nsec=833238985}, FUTEX_BITSET_MATCH_ANY <unfinished ...>
17223 <... futex resumed>)              = 0
17223 futex(0x7f74c182a400, FUTEX_WAKE_PRIVATE, 1) = 1
17076 <... futex resumed>)              = 0
17076 futex(0x7f74c182a3a8, FUTEX_WAKE_PRIVATE, 1) = 0
17223 futex(0x7f74c182a404, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
17076 futex(0x7f74c182a3a8, FUTEX_WAIT_PRIVATE, 2, NULL <unfinished ...>
17223 <... futex resumed>)              = 0
17223 futex(0x7f74c182a3a8, FUTEX_WAKE_PRIVATE, 1) = 1
17076 <... futex resumed>)              = 0
17076 futex(0x7f74c182a3a8, FUTEX_WAKE_PRIVATE, 1) = 0
17223 futex(0x7f74c182a400, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
17076 futex(0x7f74c182a3a8, FUTEX_WAIT_PRIVATE, 2, NULL <unfinished ...>
17223 <... futex resumed>)              = 0
17223 futex(0x7f74c182a3a8, FUTEX_WAKE_PRIVATE, 1) = 1
17076 <... futex resumed>)              = 0
17223 futex(0x7f74ab2d704c, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
17076 futex(0x7f74c182a3a8, FUTEX_WAKE_PRIVATE, 1) = 0
17076 futex(0x7f74ab2d704c, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
17223 <... futex resumed>)              = 0
17076 <... futex resumed>)              = 1
17223 futex(0x7f74b0165070, FUTEX_WAIT_PRIVATE, 2, NULL <unfinished ...>
17076 futex(0x7f74b0165070, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
17223 <... futex resumed>)              = -1 EAGAIN (Resource temporarily unavailable)
17076 <... futex resumed>)              = 0
17223 futex(0x7f74b0165070, FUTEX_WAKE_PRIVATE, 1 <unfinished ...>
17076 futex(0x7f74c182a404, FUTEX_WAIT_BITSET_PRIVATE, 0, {tv_sec=20705, tv_nsec=833239814}, FUTEX_BITSET_MATCH_ANY <unfinished ...>
17223 <... futex resumed>)              = 0
...
```

It would seem there are two firefox threads that makes thousands of futex calls per second with a lot of errors. There is also a lot more poll and wait4 calls. This only happens once firefox connects to keepassxc-proxy in a flatpak container.

As for why this happens, or what it means, I have no clue. I wish I did, considering how this greatly affects my laptop's battery life.

**Comment by AsavarTzeth** [comment] 2020-11-01 10:58
Closing because this has in my experience been happening intermittently with some versions of firefox and have stopped being an issue in others. Recent ones have mostly made it a non-issue.

Feel free to comment if it persists, but there isn't anything I can do about it.

**Closed by AsavarTzeth** 2020-11-01 10:58 UTC
Labels: can't reproduce, external issue, out-of-date
