### ISSUE TITLE
Unable to create a database

### ISSUE THREAD

**Issue by Tids** [flathub/org.keepassxc.KeePassXC#4] opened 2018-02-08 07:25 UTC
If I try to create a database, keepassxc will do it secessfully but the database is not visible in my filemanager.
I can also add new entries to the database, once I restart my computer, KeePass is unable to even find the Database.

So I keep losing my data on every restart, wich makes KeepassXC flatpak almost useless.

**Comment by AsavarTzeth** [comment] 2018-02-08 10:11
I managed to reproduce this. In my case I decided to create a database called "test" in my home directory. This should have added a file `~/test.kdbx`.

I did not find this file in my filesystem, however I did find a few other files:

    .xdp_test.4FPPDZ
    .xdp_test.DB7NDZ
    .xdp_test.DQIODZ

The temporary directory used during the test was `/run/user/1000/doc/fdcd59de/` and it is empty.

**Comment by RoyiAvital** [comment] 2018-05-28 04:47
I think you should add option to access `Home` with `--filesystem=home` and not just `--filesystem=/tmp`.

**Comment by AsavarTzeth** [comment] 2018-05-28 09:52
@RoyiAvital Not necessary. It currently works, using the xdg document portal which is how all sand-boxed applications should work long term.

As for why it doesn't work for @Tids or yourself, I have no idea. It may be distribution specific.

By the way `--filesystem=/tmp` is a an unrelated workaround, that would not have been necessary if keepassxc supported `xdg-run/app/appid` for temporary storage.

**Comment by AsavarTzeth** [comment] 2018-05-28 17:58
There are two ways of solving file access:

1. By statically using `--filesystem` (documented in `man flatpak-run).

    The main issue with this is that it gives all the power to the distributor. Unless you launch the app from the command line and know which flags you can use to override permissions, as a user you have no influence over permissions.

    A good comparison is how mobile operating system app permissions used to work. You had to accept permissions when you installed an app, or don't install it. In this case it is even worse, since Gnome Software (as an example) don't show you what permissions are granted.

2. You present a choice to the user, at a relevant time. For example, you wish to open a file? You are presented with a native file chooser dialog. When a user selects a file to open in an app, they obviously trust that app with that file. That file is then transferred into the sandbox.

    This is pretty much how up-to-date mobile operating systems and apps do things today. Flatpak uses [xdg-desktop-portal](https://github.com/flatpak/xdg-desktop-portal) as a framework for this type of user facing permission system.

    With this system, you don't have to grant explicit access in the build manifest, no. You as a user grant access, using the portal system, which is installed as a dependency of flatpak.

**Comment by AsavarTzeth** [comment] 2018-05-28 18:10
In other news, I tried creating a new database and nothing has changed. The are good news though. I figured out the real issue.

1. Choose to create a new database file and the file chooser opens.

2. Enter the name "keepassxc-db", then save the database.

3. Run `find /run/user/$UID/doc/ -name '*keepass*'` and you will find something like:
    ```
    /run/user/1000/doc/by-app/org.keepassxc.KeePassXC/8e6f52db/keepassxc-db.kdbx
    ```
    This is the location the file is temporarily stored and accessible both from within and outside the sandbox. The fact that the filename is correct in this location shows that there is no issue with KeePassXC.

4. Your home directory will instead contain something like:
    ```
    .xdp_keepassxc-db.BYZFJZ
    ```
    You can rename this file to `keepassxc-db.kdbx`, and open it in KeePassXC. If you made any changes to the database in previous steps you will find that this is the missing file.

Conclusion. The file is created, but for whatever reason it keeps the temporary name used by the portal framework and remains hidden to the user.

**Comment by aiamuzz** [comment] 2018-06-23 09:10
I can't open my existing password `K2Dfilename.kdbx` ... the application freezes, killing the application is the only way out !!!

**Comment by AsavarTzeth** [comment] 2019-03-19 08:40
@Tids I just tried creating a new database, including the `.kdbx` file extension explicitly and that worked.

I did some new research and this seems to be an issue specific to `xdg-desktop-portal-gtk`. I tried using `xdg-desktop-portal-kde` in which case it works as expected, with or without the `.kdbx` extension explicitly included.

See the referenced issue for more information.

**Comment by AsavarTzeth** [comment] 2019-03-24 14:05
Closing in favor of #27

**Closed by AsavarTzeth** 2019-03-24 14:05 UTC
